apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-nodes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.procilon.duckdns.org/forgejo_admin/platform-gitops.git
    targetRevision: HEAD
    path: clusters/homelab/infrastructure/longhorn-nodes
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: longhorn.io
      kind: Node
      managedFieldsManagers:
        - longhorn-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
