apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.11.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          storageMinimalAvailablePercentage: "10"
          storageReservedPercentageForDefaultDisk: "10"
        service:
          ui:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
