apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: node4
  namespace: longhorn-system
spec:
  disks:
    disk1:
      path: /var/lib/longhorn-disk1
      allowScheduling: true
      evictionRequested: false
      storageReserved: 5368709120
      tags: []
    default-disk-22b30e698d5ad776:
      path: /var/lib/longhorn
      allowScheduling: false
      evictionRequested: false
      storageReserved: 1574011699
      tags: []
